import type { Metadata } from 'next';

import './globals.css';

import Footer from './footer';
import Header from './header';

export const metadata: Metadata = {
  title: 'PetCondo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="grid min-h-dvh grid-rows-[auto_1fr_auto]">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
